--SPRINT 5 PROJECT WORKSPACE HR_PERFORMANCE_SET_2

--Questions:
SELECT * FROM HR_DEPARTMENT;
--1. Find how many Employees work under 'ABE LINCOLN PRES LIBRARY MUS2'?

SELECT COUNT(*)
FROM HR_DEPARTMENT
WHERE AGENCY = 'ABE LINCOLN PRES LIBRARY MUS2';

--2. Find the Employee list who are all working as STATIONARY ENGINEER?

SELECT *
FROM HR_DEPARTMENT
WHERE POSITION_TITLE = 'STATIONARY ENGINEER';

--3. Display the Employee list who is getting YTD Gross above 50000?

SELECT *
FROM HR_DEPARTMENT
WHERE YTD_GROSS > 50000;

--4. Display the Employee list who is working as ACCOUNTANT SUPERVISOR and YTD Gross above 50000?

SELECT *
FROM HR_DEPARTMENT
WHERE POSITION_TITLE = 'ACCOUNTANT SUPERVISOR' AND YTD_GROSS>50000;

--5. Find total Employee list work as ELECTRICIAN?

SELECT COUNT(*)
FROM HR_DEPARTMENT
WHERE POSITION_TITLE = 'ELECTRICIAN';